

CREATE TABLE Account_Transaction(
TRANS_ID INT PRIMARY KEY,
ACCOUNT_NUMBER INT,
TRANS_TYPE VARCHAR(2),
TRANS_AMT INT,
ACCOUNT_TYPE INT,
CREATED_DATE DATE,
CREATED_BY INT);





CREATE TABLE User(USER_ID INT PRIMARY KEY, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), DATE_OF_BIRTH DATE, EMAIL_ADDRESS VARCHAR(50), PASSWORD VARCHAR(50), ADDRESS VARCHAR(50), CELL_PHONE_NUMBER VARCHAR(15));



CREATE TABLE Account_Info(
ID INT PRIMARY KEY,
USER_ID INT,
ACCOUNT_NUMBER INT,
ACCOUNT_TYPE VARCHAR(3),
BALANCE INT,
CREATED_DATE DATE,
CREATED_BY INT,
LAST_UPDATED_DATE DATE,
LAST_UPDATED_BY INT
);